spring:
  application:
    name: mscards
  rabbitmq:
    host: cursomsrabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://postgres-cards:5432/bd_cards
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

eureka:
  client:
    service-url:
        defaultZone: http://cursoms-eureka-user:ecok-usr-eeuramssur@cursoms-eureka:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false

mq:
  queues:
    emissao-cartoes: emissao-cartoes

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: ./logs/log-file.log